name: Build & Push to Docker Hub

on:
  push:
    branches: [ "main" ]
    tags: [ "v*", "V*" ]   # bei v1.2.3 zusätzlich :v1.2.3 und :1.2.3
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Prepare tags
        id: prep
        run: |
          IMAGE="blackbandit1804/teamspeak-mariadb"
          TAGS="--tag ${IMAGE}:latest"
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            RAW="${GITHUB_REF_NAME}"   # z.B. v1.0.0
            CLEAN="${RAW#v}"           # 1.0.0
            TAGS="$TAGS --tag ${IMAGE}:${RAW} --tag ${IMAGE}:${CLEAN}"
          fi
          echo "tags=${TAGS}" >> "$GITHUB_OUTPUT"

      - name: Build & Push (linux/amd64)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: ${{ steps.prep.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
